version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: dotnet-api
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

    environment:
      - DOTNET_ENVIRONMENT=Development
    ports:
      - "5000:80"
 